[
	(100, [('CN=MSDC1,OU=Domain Controllers,DC=domain,DC=local', {'cn': [b'MSDC1'], 'dNSHostName': [b'msdc1.domain.local']})]),
	(100, [('CN=CTXDDC1,OU=Control,OU=Servers,DC=domain,DC=local', {'cn': [b'CTXDDC1'], 'dNSHostName': [b'ctxddc1.domain.local']})]),
	(100, [('CN=CTXVDA1,OU=SessionHosts,OU=Servers,DC=domain,DC=local', {'cn': [b'CTXVDA1'], 'dNSHostName': [b'ctxvda1.domain.local']})]),
	(100, [('CN=MSLIC1,OU=Control,OU=Servers,DC=domain,DC=local', {'cn': [b'MSLIC1'], 'dNSHostName': [b'mslic1.domain.local']})]),
	(100, [('CN=CTXVDA2,OU=SessionHosts,OU=Servers,DC=domain,DC=local', {'cn': [b'CTXVDA2'], 'dNSHostName': [b'ctxvda2.domain.local']})]),
	(100, [('CN=MSFS01,OU=Control,OU=Servers,DC=domain,DC=local', {'cn': [b'MSFS01'], 'dNSHostName': [b'msfs01.domain.local']})]),
	(100, [('CN=CTXVDA3,OU=SessionHosts,OU=Servers,DC=domain,DC=local', {'cn': [b'CTXVDA3'], 'dNSHostName': [b'CTXVDA3.domain.local']})]),
	(100, [('CN=MFAS01,OU=Control,OU=Servers,DC=domain,DC=local', {'cn': [b'MFAS01'], 'dNSHostName': [b'mfas01.domain.local']})]),
	(100, [('CN=CTXSF02,OU=Control,OU=Servers,DC=domain,DC=local', {'cn': [b'CTXSF02'], 'dNSHostName': [b'ctxsf02.domain.local']})]),
	(100, [('CN=SMNOVVMVPN1,OU=SESSION,OU=CTX,OU=Servers,DC=domain,DC=local', {'cn': [b'SMNOVVMVPN1'], 'dNSHostName': [b'smnovvmvpn1.domain.local']})]),
	(100, [('CN=SMNOVVMVPN2,OU=SessionHosts,OU=Servers,DC=domain,DC=local', {'cn': [b'SMNOVVMVPN2'], 'dNSHostName': [b'smnovvmvpn2.domain.local']})]),
	(100, [('CN=SMNOVVMVPN3,OU=SessionHosts,OU=Servers,DC=domain,DC=local', {'cn': [b'SMNOVVMVPN3'], 'dNSHostName': [b'smnovvmvpn3.domain.local']})]),
	(100, [('CN=CTXDDC2,OU=Control,OU=Servers,DC=domain,DC=local', {'cn': [b'CTXDDC2'], 'dNSHostName': [b'ctxddc2.domain.local']})]),
	(100, [('CN=MSDC2,OU=Domain Controllers,DC=domain,DC=local', {'cn': [b'MSDC2'], 'dNSHostName': [b'msdc2.domain.local']})]),
	(100, [('CN=CTXNSTF01,OU=CONTROL,OU=CTX,OU=Servers,DC=domain,DC=local', {'cn': [b'CTXNSTF01'], 'dNSHostName': [b'ctxnstf01.domain.local']})]),
	(100, [('CN=CTXNDDC01,OU=CONTROL,OU=CTX,OU=Servers,DC=domain,DC=local', {'cn': [b'CTXNDDC01'], 'dNSHostName': [b'ctxnddc01.domain.local']})]),
	(100, [('CN=CTXNLIC01,OU=CONTROL,OU=CTX,OU=Servers,DC=domain,DC=local', {'cn': [b'CTXNLIC01'], 'dNSHostName': [b'ctxnlic01.domain.local']})]),
	(100, [('CN=CTXNVDA01,OU=SESSION,OU=CTX,OU=Servers,DC=domain,DC=local', {'cn': [b'CTXNVDA01'], 'dNSHostName': [b'ctxnvda01.domain.local']})]),
	(100, [('CN=CTXNDDC02,OU=CONTROL,OU=CTX,OU=Servers,DC=domain,DC=local', {'cn': [b'CTXNDDC02'], 'dNSHostName': [b'ctxnddc02.domain.local']})]),
	(100, [('CN=CTXNFED01,OU=CONTROL,OU=CTX,OU=Servers,DC=domain,DC=local', {'cn': [b'CTXNFED01'], 'dNSHostName': [b'ctxnfed01.domain.local']})]),
	(100, [('CN=CTXNSTF02,OU=CONTROL,OU=CTX,OU=Servers,DC=domain,DC=local', {'cn': [b'CTXNSTF02'], 'dNSHostName': [b'ctxnstf02.domain.local']})]),
	(100, [('CN=WSAMZN-2A972DMI,OU=Workspaces,OU=AWS,OU=Servers,DC=domain,DC=local', {'cn': [b'WSAMZN-2A972DMI'], 'dNSHostName': [b'WSAMZN-2A972DMI.domain.local']})]),
	(100, [('CN=POCLW01,CN=Computers,DC=domain,DC=local', {'cn': [b'POCLW01'], 'dNSHostName': [b'poclw01.domain.local']})]),
	(100, [('CN=U-2PZEFM8DYL55D,CN=Computers,DC=domain,DC=local', {'cn': [b'U-2PZEFM8DYL55D'], 'dNSHostName': [b'u-2pzefm8dyl55d.domain.local']})]),
	(100, [('CN=U-2KK8TA9VSHV7H,CN=Computers,DC=domain,DC=local', {'cn': [b'U-2KK8TA9VSHV7H'], 'dNSHostName': [b'u-2kk8ta9vshv7h.domain.local']})]),
	(100, [('CN=U-192A1XPB4C5M5,CN=Computers,DC=domain,DC=local', {'cn': [b'U-192A1XPB4C5M5'], 'dNSHostName': [b'u-192a1xpb4c5m5.domain.local']})]),
	(100, [('CN=U-35RQXJZ6IHI43,CN=Computers,DC=domain,DC=local', {'cn': [b'U-35RQXJZ6IHI43'], 'dNSHostName': [b'u-35rqxjz6ihi43.domain.local']})]),
	(100, [('CN=CTXNVDA03,OU=SESSION,OU=CTX,OU=Servers,DC=domain,DC=local', {'cn': [b'CTXNVDA03'], 'dNSHostName': [b'ctxnvda03.domain.local']})]),
	(100, [('CN=CTXNVDA02,OU=SESSION,OU=CTX,OU=Servers,DC=domain,DC=local', {'cn': [b'CTXNVDA02'], 'dNSHostName': [b'ctxnvda02.domain.local']})]),
	(100, [('CN=CTXNVPN01,CN=Computers,DC=domain,DC=local', {'cn': [b'CTXNVPN01'], 'dNSHostName': [b'ctxnvpn01.domain.local']})]),
	(100, [('CN=CTXNVDA04,CN=Computers,DC=domain,DC=local', {'cn': [b'CTXNVDA04'], 'dNSHostName': [b'ctxnvda04.domain.local']})]),
	(115, [(None, ['ldap://ForestDnsZones.domain.local/DC=ForestDnsZones,DC=domain,DC=local'])]),
	(115, [(None, ['ldap://DomainDnsZones.domain.local/DC=DomainDnsZones,DC=domain,DC=local'])]),
	(115, [(None, ['ldap://domain.local/CN=Configuration,DC=domain,DC=local'])]),
	(101, [])
]
