alerting:
  alertmanagers:
  - static_configs:
    - targets: null
global:
  evaluation_interval: 60s
  scrape_interval: 60s
rule_files: null
scrape_configs:
- job_name: prometheus
  static_configs:
  - targets:
    - localhost:9090
- honor_labels: true
  job_name: sammdisc
  docker_sd_configs:
  - host: http://100.100.200.200:2375
    port: 5000
    filters:
    - name: label
      values: 
      - samm=collector
