alerting:
  alertmanagers:
  - static_configs:
    - targets: null
global:
  evaluation_interval: 15s
  scrape_interval: 15s
rule_files: null
scrape_configs:
- job_name: prometheus
  static_configs:
  - targets:
    - localhost:9090
- honor_labels: true
  job_name: samm
  static_configs:
      - targets:
        - samm-server:9090
