apiVersion: 1

datasources:
  - name: SAMM-Prometheus
    type: prometheus
    uid: c3a5e98c-6e94-44b8-b894-ae05241051b7
    url: http://172.17.0.1:9090
    access: proxy
    jsonData:
    httpMethod: POST
    manageAlerts: true
    prometheusType: Prometheus
    prometheusVersion: 2.44.0
    cacheLevel: 'High'
    disableRecordingRules: false
    incrementalQueryOverlapWindow: 10m
  - name: SAMM-Loki
    type: loki
    uid: a3b388bb-5990-45ca-a5b5-0bca47387fe1
    url: http://172.17.0.1:3100
    access: proxy
    jsonData:
      timeout: 60
      maxLines: 1000
  - uid: "fe37eb96-e778-4098-b04d-bf73e9683d48"
    orgId: 1
    name: "SAMM-CONFIG"
    type: "yesoreyeram-infinity-datasource"
    url: "http://172.17.0.1/"
    basicAuth: false
    basicAuthUser: ""
    isDefault: false
    jsonData:
      global_queries: []
    readOnly: false