{
 "title": "Processes",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "server", "label": "Server Name", "query": { "query": "label_values(instance)" } },
   {
    "name": "top_cpu",
    "label": "Top 5 CPU Filter",
    "query": {
     "query": "query_result(topk(5, rate(perfproc_percentprocessortime{instance=\"$server\",name!~\"_total|idle\"}[${__range}])))"
    }
   },
   {
    "name": "top_io",
    "label": "Top 5 IO Filter",
    "query": {
     "query": "query_result(topk(5, rate(perfproc_iodatabytespersec{instance=\"$server\",name!~\"_total|idle\"}[$__range])))"
    }
   },
   {
    "name": "top_pagefault",
    "label": "Top 5 Page Fault Filter",
    "query": {
     "query": "query_result(topk(5, rate(perfproc_pagefaultspersec{instance=\"$server\",name!~\"_total|idle\"}[$__range])))"
    }
   },
   {
    "name": "top_privbytes",
    "label": "Top 5 Priv Bytes Filter",
    "query": {
     "query": "query_result(topk(5, perfproc_privatebytes{instance=\"$server\",name!~\"_total|idle\"}))"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Process CPU",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "rate(perfproc_percentprocessortime{idprocess=~\"$top_cpu\", instance=\"$server\"}[$__rate_interval]) / rate(perfproc_timestamp_perftime{idprocess=~\"$top_cpu\", instance=\"$server\"}[$__rate_interval]) ",
     "legendFormat": "{{name}}({{idprocess}})"
    }
   ]
  },
  {
   "title": "Process Page Faults per Second",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(perfproc_pagefaultspersec{idprocess=~\"$top_pagefault\"}[$__rate_interval]) / rate(perfproc_timestamp_perftime{idprocess=~\"$top_pagefault\"}[$__rate_interval])",
     "legendFormat": "{{name}}({{idprocess}})"
    }
   ]
  },
  {
   "title": "Process IO",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(perfproc_iodatabytespersec{idprocess=~\"$top_io\"}[$__rate_interval])",
     "legendFormat": "{{name}}({{idprocess}})"
    }
   ]
  },
  {
   "title": "Process Private Bytes",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "perfproc_privatebytes{idprocess=~\"$top_privbytes\"}",
     "legendFormat": "{{name}}({{idprocess}})"
    }
   ]
  }
 ]
}