{
 "title": "Server Status",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   {
    "name": "servers",
    "label": "Servers",
    "query": {
     "query": "label_values(os_lastbootuptime,instance)"
    }
   },
   {
    "name": "active_sessions",
    "query": {
     "query": "query_result(perftssession_handlecount{name=~\"ica.*|rdp.*\",instance=\"$servers\"})"
    }
   },
   {
    "name": "disconnected_sessions",
    "query": {
     "query": "query_result(perftssession_handlecount{name=~\".*disc\",instance=\"$servers\"})"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "CPU",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "1 - rate(perfcpu_percentidletime{instance=~\"$servers\", name=\"_total\"}[5m]) / rate(perfcpu_timestamp_perftime{instance=~\"$servers\", name=\"_total\"}[5m])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "RAM",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "1 - os_freephysicalmemory{instance=~\"$servers\"} / os_totalvisiblememorysize{instance=~\"$servers\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Disk Used",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "1 - disk_freespace{instance=~\"$servers\"} / disk_size{instance=~\"$servers\"}",
     "legendFormat": "{{caption}}"
    }
   ]
  },
  {
   "title": "Pagefile Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "pagefile_currentusage{instance=~\"$servers\"} / pagefile_allocatedbasesize{instance=~\"$servers\"}",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Network Transfer",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "rate(perfnic_bytesreceivedpersec{instance=~\"$servers\", name!~\"isatap.*\"}[$__rate_interval])",
     "legendFormat": "Rx_{{name}}"
    },
    {
     "expr": "- rate(perfnic_bytessentpersec{instance=~\"$servers\", name!~\"isatap.*\"}[$__rate_interval])",
     "legendFormat": "Tx_{{name}}"
    }
   ]
  },
  {
   "title": "Disk transfer",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "rate(perfdisk_avgdiskbytesperread{instance=~\"$servers\",name=\"_total\"}[$__rate_interval]) / rate(perfdisk_avgdisksecperread{instance=~\"$servers\",name=\"_total\"}[$__rate_interval])",
     "legendFormat": "read"
    },
    {
     "expr": "rate(perfdisk_avgdiskbytesperwrite{instance=~\"$servers\",name=\"_total\"}[$__rate_interval])/ rate(perfdisk_avgdisksecperwrite{instance=~\"$servers\",name=\"_total\"}[$__rate_interval])",
     "legendFormat": "write"
    }
   ]
  },
  {
   "title": "Remote Sessions",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "targets": [
    {
     "expr": "count by (instance) (perftssession_handlecount{instance=~\"$servers\",name=~\"ica.*|rdp.*\"})",
     "legendFormat": "active_sessions_{{instance}}"
    },
    {
     "expr": "count by (instance) (perftssession_handlecount{instance=~\"$servers\",name=~\".*disc\"})",
     "legendFormat": "disconnected_{{instance}}"
    }
   ]
  }
 ]
}