{
 "title": "Delivery Groups",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "desktopgroup",
    "label": "Delivery Group",
    "query": {
     "query": "label_values(desktopgroup_name)"
    }
   },
   {
    "name": "dnsname",
    "label": "Machines",
    "query": {
     "query": "query_result(ctxmachine_isinmaintenancemode{desktopgroup_name=\"$desktopgroup\"})"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Total Machines",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(ctxmachine_isinmaintenancemode{desktopgroup_name=\"$desktopgroup\"})"
    }
   ]
  },
  {
   "title": "Machines in Maintenance",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 7, "x": 4, "y": 0 },
   "targets": [
    {
     "expr": "sum(ctxmachine_isinmaintenancemode{desktopgroup_name=\"$desktopgroup\"})",
     "legendFormat": "InMaintenance"
    }
   ]
  },
  {
   "title": "Registered",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 7, "x": 11, "y": 0 },
   "targets": [
    {
     "expr": "count(ctxmachine_currentregistrationstate{desktopgroup_name=\"$desktopgroup\"} == 1)",
     "legendFormat": "Registered"
    },
    {
     "expr": "count(ctxmachine_currentregistrationstate{desktopgroup_name=\"$desktopgroup\"} == 2)",
     "legendFormat": "Unregistered"
    }
   ]
  },
  { "title": "Total Delivery Group", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 } },
  {
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 7 },
   "targets": [
    {
     "expr": "count(ctxsession_connectionstate{machine_dnsname=~\"$dnsname\"}) == 0",
     "legendFormat": "Unknown"
    },
    {
     "expr": "count(ctxsession_connectionstate{machine_dnsname=~\"$dnsname\"} == 1)",
     "legendFormat": "Connected"
    },
    {
     "expr": "count(ctxsession_connectionstate{machine_dnsname=~\"$dnsname\"} == 2)",
     "legendFormat": "Disconnected"
    },
    {
     "expr": "count(ctxsession_connectionstate{machine_dnsname=~\"$dnsname\"} == 5)",
     "legendFormat": "Active"
    },
    {
     "expr": "count(ctxsession_connectionstate{machine_dnsname=~\"$dnsname\"} == 4)",
     "legendFormat": "Preparing Session"
    },
    {
     "expr": "count(ctxsession_connectionstate{machine_dnsname=~\"$dnsname\"} == 6)",
     "legendFormat": "Reconnecting"
    },
    {
     "expr": "count(ctxsession_connectionstate{machine_dnsname=~\"$dnsname\"} == 7)",
     "legendFormat": "Non Brokered Session"
    },
    {
     "expr": "count(ctxsession_connectionstate{machine_dnsname=~\"$dnsname\"} == 8)",
     "legendFormat": "Other"
    },
    {
     "expr": "count(ctxsession_connectionstate{machine_dnsname=~\"$dnsname\"} == 9)",
     "legendFormat": "Pending"
    }
   ]
  },
  {
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 7 },
   "targets": [
    {
     "expr": "sum(ctxmachine_currentloadindex_effectiveloadindex{desktopgroup_name=\"$desktopgroup\"}) / count(ctxmachine_isinmaintenancemode{desktopgroup_name=\"$desktopgroup\"})",
     "legendFormat": "Catalog LoadIndex"
    }
   ]
  },
  {
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 7, "x": 16, "y": 7 },
   "targets": [
    {
     "expr": "count(ctxmachine_currentloadindex_effectiveloadindex{desktopgroup_name=\"$desktopgroup\"} == 10000)",
     "legendFormat": "Servers Full"
    },
    {
     "expr": "count(ctxmachine_currentloadindex_effectiveloadindex{desktopgroup_name=\"$desktopgroup\"} < 10000)",
     "legendFormat": "Servers Available"
    }
   ]
  },
  { "title": "Per machine", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 15 } },
  {
   "title": "Sessions",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "count by(machine_dnsname) (ctxsession_connectionstate{machine_dnsname=~\"$dnsname\"})",
     "legendFormat": "{{label_name}}"
    }
   ]
  },
  {
   "title": "Load Evaluator",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 16 },
   "targets": [
    {
     "expr": "ctxmachine_currentloadindex_effectiveloadindex{desktopgroup_name=\"$desktopgroup\"}",
     "legendFormat": "{{dnsname}}"
    }
   ]
  },
  { "title": "Row title", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 24 } },
  {
   "title": "LoadIndex Memory",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 25 },
   "targets": [
    {
     "expr": "ctxmachine_currentloadindex_memory{dnsname=~\"$dnsname\"}",
     "legendFormat": "{{dnsname}}"
    }
   ]
  },
  {
   "title": "LoadIndex CPU",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 25 },
   "targets": [
    {
     "expr": "ctxmachine_currentloadindex_cpu{dnsname=~\"$dnsname\"}",
     "legendFormat": "{{dnsname}}"
    }
   ]
  },
  {
   "title": "LoadIndex Sessions",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 25 },
   "targets": [
    {
     "expr": "ctxmachine_currentloadindex_sessioncount{dnsname=~\"$dnsname\"}",
     "legendFormat": "{{dnsname}}"
    }
   ]
  },
  {
   "title": "LoadIndex Disk",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 25 },
   "targets": [
    {
     "expr": "ctxmachine_currentloadindex_disk{dnsname=~\"$dnsname\"}",
     "legendFormat": "{{dnsname}}"
    }
   ]
  }
 ]
}