{
 "title": "Machine Catalogs",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "catalog", "label": "Catalog", "query": { "query": "label_values(catalog_name)" } },
   {
    "name": "dnsname",
    "label": "Machines",
    "query": {
     "query": "query_result(ctxmachine_isinmaintenancemode{catalog_name=\"$catalog\"})"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Total Machines",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(ctxmachine_isinmaintenancemode{catalog_name=\"$catalog\"})"
    }
   ]
  },
  {
   "title": "Machines in Maintenance",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 7, "x": 4, "y": 0 },
   "targets": [
    {
     "expr": "sum(ctxmachine_isinmaintenancemode{catalog_name=\"$catalog\"})",
     "legendFormat": "InMaintenance"
    }
   ]
  },
  {
   "title": "Registered",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 7, "x": 11, "y": 0 },
   "targets": [
    {
     "expr": "count(ctxmachine_currentregistrationstate{catalog_name=\"$catalog\"} == 1)",
     "legendFormat": "Registered"
    },
    {
     "expr": "count(ctxmachine_currentregistrationstate{catalog_name=\"$catalog\"} == 2)",
     "legendFormat": "Unregistered"
    }
   ]
  },
  { "title": "Total Catalog", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 } },
  {
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 7 },
   "targets": [
    {
     "expr": "count(ctxsession_connectionstate == 0)",
     "legendFormat": "Unknown"
    },
    {
     "expr": "count(ctxsession_connectionstate == 1)",
     "legendFormat": "Connected"
    },
    {
     "expr": "count(ctxsession_connectionstate == 2)",
     "legendFormat": "Disconnected"
    },
    {
     "expr": "count(ctxsession_connectionstate == 5)",
     "legendFormat": "Active"
    },
    {
     "expr": "count(ctxsession_connectionstate == 4)",
     "legendFormat": "Preparing Session"
    },
    {
     "expr": "count(ctxsession_connectionstate == 6)",
     "legendFormat": "Reconnecting"
    },
    {
     "expr": "count(ctxsession_connectionstate == 7)",
     "legendFormat": "Non Brokered Session"
    },
    {
     "expr": "count(ctxsession_connectionstate == 8)",
     "legendFormat": "Other"
    },
    {
     "expr": "count(ctxsession_connectionstate == 9)",
     "legendFormat": "Pending"
    }
   ]
  },
  {
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 7 },
   "targets": [
    {
     "expr": "sum(ctxmachine_currentloadindex_effectiveloadindex) / count(ctxmachine_isinmaintenancemode)",
     "legendFormat": "Catalog LoadIndex"
    }
   ]
  },
  {
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 7, "x": 16, "y": 7 },
   "targets": [
    {
     "expr": "count(ctxmachine_currentloadindex_effectiveloadindex{catalog_name=\"$catalog\"}) == 10000",
     "legendFormat": "Servers Full"
    },
    {
     "expr": "count(ctxmachine_currentloadindex_effectiveloadindex{catalog_name=\"$catalog\"}) < 10000",
     "legendFormat": "Servers Available"
    }
   ]
  },
  { "title": "Per machine", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 15 } },
  {
   "title": "Sessions",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "count by(machine_dnsname) (ctxsession_connectionstate{machine_dnsname=~\"$dnsname\"})",
     "legendFormat": "{{label_name}}"
    }
   ]
  },
  {
   "title": "Load Evaluator",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 16 },
   "targets": [
    {
     "expr": "ctxmachine_currentloadindex_effectiveloadindex{catalog_name=\"$catalog\"}",
     "legendFormat": "{{dnsname}}"
    }
   ]
  },
  { "title": "Row title", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 24 } },
  {
   "title": "LoadIndex Memory",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 25 },
   "targets": [
    {
     "expr": "ctxmachine_currentloadindex_memory{catalog_name=\"$catalog\"}",
     "legendFormat": "{{dnsname}}"
    }
   ]
  },
  {
   "title": "LoadIndex CPU",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 25 },
   "targets": [
    {
     "expr": "ctxmachine_currentloadindex_cpu{catalog_name=\"$catalog\"}",
     "legendFormat": "{{dnsname}}"
    }
   ]
  },
  {
   "title": "LoadIndex Sessions",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 25 },
   "targets": [
    {
     "expr": "ctxmachine_currentloadindex_sessioncount{catalog_name=\"$catalog\"}",
     "legendFormat": "{{dnsname}}"
    }
   ]
  },
  {
   "title": "LoadIndex Disk",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 25 },
   "targets": [
    {
     "expr": "ctxmachine_currentloadindex_disk{catalog_name=\"$catalog\"}",
     "legendFormat": "{{dnsname}}"
    }
   ]
  }
 ]
}