{
 "title": "Load Balancing",
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "5m",
 "templating": {
  "list": [
   {
    "name": "instance",
    "label": "Instance",
    "query": {
     "query": "query_result(nsstats_rescpuusage{syshighavailabilitymode=\"primary\"})"
    }
   },
   {
    "name": "vserver",
    "label": "VServer",
    "query": {
     "query": "query_result(vserverstats_vsvrcurclntconnections{instance=\"$instance\"})"
    }
   }
  ]
 },
 "panels": [
  { "title": "Status", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Health",
   "type": "bargauge",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "vserverstats_vsvrhealth{instance=\"$instance\", vsvrname=~\"$vserver\", vsvrentitytype=\"loadbalancing\"}",
     "legendFormat": "{{vsvrname}}"
    }
   ]
  },
  {
   "title": "Services",
   "type": "barchart",
   "gridPos": { "h": 6, "w": 4, "x": 6, "y": 1 },
   "targets": [
    {
     "expr": "vserverstats_vsvrcurservicesdown{instance=\"$instance\", vsvrname=~\"$vserver\", vsvrentitytype=\"loadbalancing\"}",
     "legendFormat": "DOWN"
    },
    {
     "expr": "vserverstats_vsvrcurservicesoutofsvc{instance=\"$instance\", vsvrname=~\"$vserver\", vsvrentitytype=\"loadbalancing\"}",
     "legendFormat": "OUTOFSVC"
    },
    {
     "expr": "vserverstats_vsvrcurservicesup{instance=\"$instance\", vsvrname=~\"$vserver\", vsvrentitytype=\"loadbalancing\"}",
     "legendFormat": "UP"
    }
   ]
  },
  { "title": "Traffic", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 } },
  {
   "title": "Requests per sec",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "rate(vserverstats_vsvrtotalrequests{instance=\"$instance\", vsvrname=~\"$vserver\"}[$__rate_interval])",
     "legendFormat": "{{vsvrname}}"
    }
   ]
  },
  {
   "title": "Response per sec",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "rate(vserverstats_vsvrtotalresponses{instance=\"$instance\", vsvrname=~\"$vserver\"}[$__rate_interval])",
     "legendFormat": "{{vsvrname}}"
    }
   ]
  },
  {
   "title": "Request Bytes per sec",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "rate(vserverstats_vsvrtotalrequestbytes{instance=\"$instance\", vsvrname=~\"$vserver\"}[$__rate_interval])",
     "legendFormat": "{{vsvrname}}"
    }
   ]
  },
  {
   "title": "Response Bytes per sec",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "rate(vserverstats_vsvrtotalresponsebytes{instance=\"$instance\", vsvrname=~\"$vserver\"}[$__rate_interval])",
     "legendFormat": "{{vsvrname}}"
    }
   ]
  },
  {
   "title": "Connections",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 18 },
   "targets": [
    {
     "expr": "vserverstats_vsvrcurclntconnections{instance=\"$instance\", vsvrname=~\"$vserver\"}",
     "legendFormat": "Clients-{{vsvrname}}"
    },
    {
     "expr": "vserverstats_vsvrcurclntconnections{instance=\"$instance\", vsvrname=~\"$vserver\"}",
     "legendFormat": "Servers-{{vsvrname}}"
    }
   ]
  },
  { "title": "Errors", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 23 } },
  {
   "title": "Panel Title",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "targets": [
    {
     "expr": "rate(vserverstats_vsvrinvalidrequestresponse{instance=\"$instance\", vsvrname=~\"$vserver\"}[$__rate_interval])",
     "legendFormat": "InvalidReqRes-{{vsvrname}}"
    },
    {
     "expr": "rate(vserverstats_vsvrinvalidrequestresponsedropped{instance=\"$instance\", vsvrname=~\"$vserver\"}[$__rate_interval])",
     "legendFormat": "InvalidReqResDrop-{{vsvrname}}"
    }
   ]
  }
 ]
}